apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: nats
  name: nats
spec:
  ports:
  - name: "4222"
    port: 4222
    targetPort: 4222
  - name: "8222"
    port: 8222
    targetPort: 8222
  selector:
    io.kompose.service: nats
status:
  loadBalancer: {}
